#!/usr/bin/env node

import { Command } from 'commander';
import chalk from 'chalk';
import * as fs from 'fs';

const program = new Command();

program
  .name('ai-streaming')
  .description('SSE streaming utilities for LLM responses. Generate streaming code for Next.js, Express.')
  .version('1.0.0');

// Init command
program
  .command('init')
  .description('Generate streaming utilities for your project')
  .option('-d, --dir <path>', 'Output directory', './lib/streaming')
  .option('-f, --framework <framework>', 'Framework (nextjs|express)', 'nextjs')
  .option('--js', 'Generate JavaScript')
  .action((options) => {
    const ext = options.js ? 'js' : 'ts';
    const dir = options.dir;

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    // Utils file
    const utilsCode = `// SSE Stream Utilities
// Generated by ai-streaming

export function createSSEStream() {
  const encoder = new TextEncoder();
  let controller${options.js ? '' : ': ReadableStreamDefaultController<Uint8Array>'};

  const stream = new ReadableStream({
    start(c) {
      controller = c;
    },
  });

  return {
    stream,
    write(data${options.js ? '' : ': string'}) {
      controller.enqueue(encoder.encode(\`data: \${data}\\n\\n\`));
    },
    writeJSON(data${options.js ? '' : ': any'}) {
      controller.enqueue(encoder.encode(\`data: \${JSON.stringify(data)}\\n\\n\`));
    },
    close() {
      controller.enqueue(encoder.encode('data: [DONE]\\n\\n'));
      controller.close();
    },
    error(err${options.js ? '' : ': Error'}) {
      controller.enqueue(encoder.encode(\`data: \${JSON.stringify({ error: err.message })}\\n\\n\`));
      controller.close();
    },
  };
}

export function sseHeaders() {
  return {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive',
  };
}
`;

    fs.writeFileSync(`${dir}/utils.${ext}`, utilsCode);
    console.log(chalk.green(`✓ Created ${dir}/utils.${ext}`));

    // OpenAI streaming
    const openaiCode = `// OpenAI Streaming
// Generated by ai-streaming

import OpenAI from 'openai';
import { createSSEStream, sseHeaders } from './utils';

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

${options.js ? '' : `interface Message {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

`}export async function streamOpenAI(messages${options.js ? '' : ': Message[]'}, options${options.js ? ' = {}' : '?: { model?: string; systemPrompt?: string }'}) {
  const { model = 'gpt-4-turbo', systemPrompt } = options || {};
  const { stream, write, close, error } = createSSEStream();

  const apiMessages${options.js ? '' : ': OpenAI.ChatCompletionMessageParam[]'} = [];
  if (systemPrompt) apiMessages.push({ role: 'system', content: systemPrompt });
  apiMessages.push(...messages);

  (async () => {
    try {
      const response = await openai.chat.completions.create({
        model,
        messages: apiMessages,
        stream: true,
      });

      for await (const chunk of response) {
        const content = chunk.choices[0]?.delta?.content;
        if (content) write(content);
      }
      close();
    } catch (e) {
      error(e${options.js ? '' : ' as Error'});
    }
  })();

  return new Response(stream, { headers: sseHeaders() });
}

export async function* streamOpenAIGenerator(messages${options.js ? '' : ': Message[]'}, options${options.js ? ' = {}' : '?: { model?: string; systemPrompt?: string }'}) {
  const { model = 'gpt-4-turbo', systemPrompt } = options || {};

  const apiMessages${options.js ? '' : ': OpenAI.ChatCompletionMessageParam[]'} = [];
  if (systemPrompt) apiMessages.push({ role: 'system', content: systemPrompt });
  apiMessages.push(...messages);

  const response = await openai.chat.completions.create({
    model,
    messages: apiMessages,
    stream: true,
  });

  for await (const chunk of response) {
    const content = chunk.choices[0]?.delta?.content;
    if (content) yield content;
  }
}
`;

    fs.writeFileSync(`${dir}/openai.${ext}`, openaiCode);
    console.log(chalk.green(`✓ Created ${dir}/openai.${ext}`));

    // Client consumption
    const clientCode = `// Client-Side Stream Consumption
// Generated by ai-streaming

export async function consumeStream(
  response${options.js ? '' : ': Response'},
  onChunk${options.js ? '' : '?: (chunk: string) => void'}
)${options.js ? '' : ': Promise<string>'} {
  const reader = response.body?.getReader();
  if (!reader) throw new Error('No response body');

  const decoder = new TextDecoder();
  let fullText = '';

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    const chunk = decoder.decode(value);
    const lines = chunk.split('\\n');

    for (const line of lines) {
      if (line.startsWith('data: ')) {
        const data = line.slice(6);
        if (data === '[DONE]') continue;

        try {
          const parsed = JSON.parse(data);
          if (parsed.error) throw new Error(parsed.error);
        } catch {
          fullText += data;
          onChunk?.(data);
        }
      }
    }
  }

  return fullText;
}
`;

    fs.writeFileSync(`${dir}/client.${ext}`, clientCode);
    console.log(chalk.green(`✓ Created ${dir}/client.${ext}`));

    // Framework-specific route
    if (options.framework === 'nextjs') {
      const routeCode = `// Next.js App Router API Route
// Generated by ai-streaming
// Save as: app/api/chat/route.ts

import { streamOpenAI } from '@/lib/streaming/openai';

export async function POST(req${options.js ? '' : ': Request'}) {
  const { messages } = await req.json();
  return streamOpenAI(messages);
}
`;

      fs.writeFileSync(`${dir}/route.example.${ext}`, routeCode);
      console.log(chalk.green(`✓ Created ${dir}/route.example.${ext}`));
    } else {
      const expressCode = `// Express Route
// Generated by ai-streaming

import express from 'express';
import { streamOpenAIGenerator } from './openai';

const router = express.Router();

router.post('/chat', async (req, res) => {
  const { messages } = req.body;

  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');

  try {
    for await (const chunk of streamOpenAIGenerator(messages)) {
      res.write(\`data: \${chunk}\\n\\n\`);
    }
    res.write('data: [DONE]\\n\\n');
    res.end();
  } catch (error) {
    res.write(\`data: \${JSON.stringify({ error: 'Stream failed' })}\\n\\n\`);
    res.end();
  }
});

export default router;
`;

      fs.writeFileSync(`${dir}/routes.${ext}`, expressCode);
      console.log(chalk.green(`✓ Created ${dir}/routes.${ext}`));
    }

    // Index file
    const indexCode = `// Streaming Utilities
// Generated by ai-streaming

export * from './utils';
export * from './openai';
export * from './client';
`;

    fs.writeFileSync(`${dir}/index.${ext}`, indexCode);
    console.log(chalk.green(`✓ Created ${dir}/index.${ext}`));

    console.log(chalk.cyan('\n✅ Streaming utilities generated!'));
    console.log(chalk.gray('\nUsage:'));
    console.log(chalk.gray(`  import { streamOpenAI } from '${dir}';`));
    console.log(chalk.gray(`  return streamOpenAI(messages);`));
    console.log(chalk.gray('\nDon\'t forget to set OPENAI_API_KEY in your .env file'));
  });

// Info command
program
  .command('info')
  .description('Show streaming information and examples')
  .action(() => {
    console.log(chalk.cyan('\n📡 SSE Streaming for LLMs\n'));
    
    console.log(chalk.bold('What is SSE?'));
    console.log('  Server-Sent Events allow servers to push data to clients');
    console.log('  in real-time. Perfect for streaming LLM responses.\n');

    console.log(chalk.bold('Supported Providers:'));
    console.log('  • OpenAI (GPT-4, GPT-3.5)');
    console.log('  • Anthropic (Claude 3)\n');

    console.log(chalk.bold('Supported Frameworks:'));
    console.log('  • Next.js App Router');
    console.log('  • Express/Fastify');
    console.log('  • Vanilla Node.js\n');

    console.log(chalk.bold('Quick Start:'));
    console.log(chalk.gray('  npx ai-streaming init'));
    console.log(chalk.gray('  npx ai-streaming init --framework express\n'));
  });

program.parse();
