// Generated by ReScript, PLEASE EDIT WITH CARE


function classify(arrayable) {
  if (Array.isArray(arrayable)) {
    return {
      TAG: "Array",
      _0: arrayable
    };
  } else {
    return {
      TAG: "Single",
      _0: arrayable
    };
  }
}

let Arrayable = {
  classify: classify
};

let Mutable = {};

export {
  Arrayable,
  Mutable,
}
/* No side effect */
