// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sury from "sury";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let empty = "";

let dynamic = "[]";

let Path = {
  empty: empty,
  dynamic: dynamic
};

let Exn = /* @__PURE__ */Primitive_exceptions.create("S.Exn");

Sury.$res_setExnId(Exn);

let none = 0;

let async = 1;

let Flag = {
  none: none,
  async: async
};

let $$Error = {};

function refine(schema, refiner, error, path) {
  return Sury.refine(schema, refiner, {
    error: error,
    path: path
  });
}

function to(from, target) {
  if (from === target) {
    return from;
  } else {
    return Sury.to(from, target);
  }
}

function decoder(from, to) {
  return Sury.decoder(Sury.reverse(from), to);
}

function asyncDecoder(from, to) {
  return Sury.asyncDecoder(Sury.reverse(from), to);
}

function parseOrThrow(any, to) {
  return Sury.parser(to)(any);
}

function parseAsyncOrThrow(any, to) {
  return Sury.asyncParser(to)(any);
}

function decodeOrThrow(any, from, to) {
  return Sury.decoder(Sury.reverse(from), to)(any);
}

function decodeAsyncOrThrow(any, from, to) {
  return Sury.asyncDecoder(Sury.reverse(from), to)(any);
}

let Schema = {};

let $$Object = {};

let Tuple = {};

function tuple1(v0) {
  return Sury.tuple(s => s.item(0, v0));
}

function tuple2(v1, v2) {
  return Sury.schema([
    v1,
    v2
  ]);
}

function tuple3(v1, v2, v3) {
  return Sury.schema([
    v1,
    v2,
    v3
  ]);
}

let Option = {};

let Id = {};

let Metadata = {
  Id: Id
};

export {
  Path,
  Exn,
  Flag,
  $$Error,
  refine,
  to,
  decoder,
  asyncDecoder,
  parseOrThrow,
  parseAsyncOrThrow,
  decodeOrThrow,
  decodeAsyncOrThrow,
  Schema,
  $$Object,
  Tuple,
  tuple1,
  tuple2,
  tuple3,
  Option,
  Metadata,
}
/*  Not a pure module */
