// Generated by ReScript, PLEASE EDIT WITH CARE


let Issue = {};

function classify(t) {
  if (t.issues) {
    return {
      TAG: "Error",
      _0: t
    };
  } else {
    return {
      TAG: "Ok",
      _0: t
    };
  }
}

let Result = {
  classify: classify
};

let JsonSchema = {};

export {
  Issue,
  Result,
  JsonSchema,
}
/* No side effect */
